### ISSUE TITLE
Start doesnt work

### ISSUE THREAD

**Issue by SCOOTSS** [Nookbot/Nookbot#14]
Whenever I run the 'node start index.js' it returns an error code

any help?

**Comment by Phoenix1128** [comment]
Could you provide the error you receive?

**Comment by SCOOTSS** [comment]
I will try and send it to you but from memory it's goes something like 'Start isn't a file in Nookbot'

I don't really know, give me an hour and ill come back to you with the real one.

**Comment by SCOOTSS** [comment]
Wait nvm i got it working
