### ISSUE TITLE
Is there a way to create reaction-role messages like in the ANCH server?

### ISSUE THREAD

**Issue by SCOOTSS** [Nookbot/Nookbot#15]

**Comment by Phoenix1128** [comment]
You can find that on the [develop branch](https://github.com/Nookbot/Nookbot/tree/develop/)

**Comment by SCOOTSS** [comment]
Where under the develop branch can i find it? the only thing I have found is the add role command?

**Comment by Phoenix1128** [comment]
Answered (#16)
