### ISSUE TITLE
Where under the 'Develop' Branch can I find reaction-roles?

### ISSUE THREAD

**Issue by SCOOTSS** [Nookbot/Nookbot#16]

**Comment by Phoenix1128** [comment]
Reaction roles are first loaded in the [ready](https://github.com/Nookbot/Nookbot/blob/master/events/ready.js) event then when I member reacts to a message the [messageReactionAdd](https://github.com/Nookbot/Nookbot/blob/master/events/messageReactionAdd.js) event is triggered. Same goes for the [messageReactionRemove](https://github.com/Nookbot/Nookbot/blob/master/events/messageReactionRemove.js) event.

**Comment by cheesycod** [comment]
Is there a way for the user to make reaction roles through a command?

**Comment by Phoenix1128** [comment]
You can only add reaction role menus using the `eval` command. The reactionRoleDB is set up as so:

    'message ID' => {
      type: 'type',                                  // Types can be 'remove', 'exclusive', 'multiple', or 'restricted'
      channel: 'channel ID',                         // The channel ID
      time: time,                                   // Only needed in restricted. The amount of time a user needs to be on the server for
      reactions: { 'identifier': 'role ID' }       // The identifier of the emoji and ID of the role to associate with it
    }

So if I wanted to add a multiple reaction role menu, I would use the following eval command:

    .eval
    client.reactionRoleDB.set('701203720200912966', {
      type: 'multiple',
      channel: '538940838441517068''
      reactions: {
        '%F0%9F%8E%AE': '588955307817041946',
        '%F0%9F%8E%8A': '588955576562614273',
      }
    }

**Comment by cheesycod** [comment]
Ummm... what exactly is the first argument to client.reactionroledb.set

**Comment by Phoenix1128** [comment]
The ID of the message to listen to reactions on. You can find out how to retrieve IDs by following [this link](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-).
