### ISSUE TITLE
cant install better sqlite pool

### ISSUE THREAD

**Issue by YaEpiO** [Nookbot/Nookbot#19]
when i try to install it multiple errors pop up saying:
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\yaepio\Nookbot\node_modules\.staging\mkdirp-classic-ed23b74f\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\yaepio\Nookbot\node_modules\.staging\moment-c48a2688\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\yaepio\Nookbot\node_modules\.staging\mkdirp-classic-ed23b74f\index.js'

etc.

**Comment by Phoenix1128** [comment]
In `package.json` could you try deleting the `ref` module in the dependencies object

**Comment by YaEpiO** [comment]
The error changed a bit, but still getting an error. I'm also getting this #20

**Comment by YaEpiO** [comment]
nevermind, that seemed to fix it thansk
