### ISSUE TITLE
What software do you use to run the bot?

### ISSUE THREAD

**Issue by BrendanDenzel** [Nookbot/Nookbot#33]

**Comment by Phoenix1128** [comment]
Instructions can again be found in the [wiki](https://github.com/Nookbot/Nookbot/wiki). Specifically the [Hosting](https://github.com/Nookbot/Nookbot/wiki/Hosting) page.

**Comment by BrendanDenzel** [comment]
I still haven’t found my answer like I’m using visual studio code what do you use on your computer
