### ISSUE TITLE
[FEATURE] Dynamic Slow Mode

### ISSUE THREAD

**Issue by crock** [Nookbot/Nookbot#5]
![image](https://user-images.githubusercontent.com/8924090/77787403-e07baa80-7035-11ea-8d77-12e45ec3879a.png)

**Comment by chowdapowa9** [comment]
Dynamic slowmode is a concerning feature to me. It'd mean giving the bot the permission to delete channels, and I don't think that's a great idea. I also don't know if it's that big of a deal to need to dynamically change slowmode, versus how complicated and risky it'd be to set up.

**Comment by Phoenix1128** [comment]
Dynamic slowmode was seen as too dangerous and unnecessary. Implemented a slowmode command instead (c7f988f5a572f05d956b602bb658187dc75fbe6b).
