### ISSUE TITLE
[FEATURE] Reaction-based Server Verification

### ISSUE THREAD

**Issue by crock** [Nookbot/Nookbot#6]

**Comment by chowdapowa9** [comment]
This is now fully and easily possible now that reaction roles are done with Nookbot, but the question is still about if we want to do things this way, and if this is the best direction to take the server in.

**Comment by crock** [comment]
@chowdapowa9  The owner of the server personally requested this feature as top priority.

**Comment by chowdapowa9** [comment]
I'm woefully aware, but much has changed in the 23 days since this was thought of being a useful feature.

**Comment by Phoenix1128** [comment]
With the inclusion of the trade and voice gates, this doesn't seem to be the direction we wish to go in.
