### ISSUE TITLE
[FEATURE] Banned Words Filtering System

### ISSUE THREAD

**Issue by crock** [Nookbot/Nookbot#7]

**Comment by crock** [comment]
![image](https://user-images.githubusercontent.com/8924090/77850785-bbf11100-71a2-11ea-99a5-8995174d3fca.png)

**Comment by DnOberon** [comment]
@crock how interested are you in still making this happen?

**Comment by crock** [comment]
@DnOberon I don't have time to do these myself anymore. All of the feature request issues I created in this repo were personally requested by Brea, the owner of the ACNH Discord.

**Comment by DnOberon** [comment]
Could you potentially put me in contact with Brea? That way I can get more
information about the request from them instead of bugging you.

**Comment by Phoenix1128** [comment]
@DnOberon I’ve already built this feature and currently putting it through some testing before pushing it.

**Comment by DnOberon** [comment]
@Phoenix1128 cool - I'd love to see how you implemented it.

**Comment by therealprocyon** [comment]
Could it work better on words if a regex or similar could be implemented? Such that you can filter on bypassing word bans? Also: some words are banned but could get unbanned if a context filter is added with regex... I'm not 100% sure, but it could take away some confusion as well as some words could get unbanned as long as the context would be filtered. Not 100% sure if you want that but it could help. I know of a bot that filters even corrupted characters etc. maybe it could be used as an example...

**Comment by Phoenix1128** [comment]
Bots, unfortunately, cannot read context perfectly, even with regex. That would require some AI technology that we don't have the time or energy to invest in. While some innocent messages would pass through, using regex, there would still be some false positives and would increase the workload for our moderators.

Not to mention, the banned words filter is not yet implemented in Nookbot, hence why this feature issue is still open.

**Comment by therealprocyon** [comment]
Ah okay, I know of a bot that has implemented some interesting things and features... Including Unicode sanitization. Aside of that: regex or whatever could technically filter stuff even without machine learning. For instance: filtering on certain combined terms. I just know too little about git to add some extra stuff for you...

**Comment by Phoenix1128** [comment]
Commit dec227d8e87477b3752ed0ddb604c8f19bc76c68 to the develop branch has seen this. We already have the ability to filter on phrases and combined terms using an external package. It just has not been implemented yet.

**Comment by Phoenix1128** [comment]
Completed with https://github.com/Nookbot/Nookbot/commit/dec227d8e87477b3752ed0ddb604c8f19bc76c68 and other subsequent commits to the develop branch. May expand on it in the future.
